# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='gmapkey',
            field=models.CharField(max_length=100, verbose_name='google api key'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='google_password',
            field=models.CharField(max_length=100, verbose_name='your password'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, default=18.045008, max_digits=8, verbose_name='your current latitude'),
        ),
    ]
