# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonbot', '0002_auto_20160801_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='google_email',
            field=models.EmailField(max_length=254, verbose_name='your google email'),
        ),
    ]
